### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by Hye-Dev** [Hye-Ararat/Ararat#14]
- [x] List servers user has access to
- [x] Display main network configuration
- [x] Live Resource Usage
- [x] Online/Offline Indicators
- [ ] Custom Magma Cube Icons

**Comment by itzTheMeow** [comment]
does creating servers via gui fall under this

**Comment by Hye-Dev** [comment]
No. Creating servers in the GUI is going to be on the Admin section. Admin Section tasks will be added after the client area is completed.

**Comment by itzTheMeow** [comment]
ah

**Comment by Hye-Dev** [comment]
Everything except OS display/server-icon.png has been completed here. Our internal development team does not see that as a priority, so we leave this issue to be completed by a pull request
