### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by Plactrix** [Hye-Ararat/Ararat#174]
is trying to steal ma credentials
veri veri bad
![image](https://github.com/Hye-Ararat/Ararat/assets/48103197/d273b057-54d3-464d-aa38-0cd5c6f8306a)

**Comment by Plactrix** [comment]
how to reproduce: literally just login to ararat on a windows computer :skull:

**Comment by DeveloperNeon** [comment]
+1

**Comment by Hye-Dev** [comment]
Unfortunately I'm not able to reproduce this issue.
